# **HW2 -> Hanoi Towers**

In [7]:
import numpy as np
#N disk defintion and population of chromosomes
n = 3
n_pop = 5

In [39]:
#Towers definition
def create_towers(n):
    """
    Create towers
    """
    t1 = []
    t2 = []
    t3 = []

    values = np.arange(n)+1

    for i in range (n):
        t1.append(values[i])

    t1.reverse()
    return t1,t2,t3

In [40]:
create_towers(n)

([3, 2, 1], [], [])

In [44]:
#Chromosomes creation
popu = []

for i in range(n_pop):
    popu.append(np.random.randint(6,size = 10))

#adding optimal solution
popu.append(np.array([1,0,5,1,2,3,1,1,1,1]))
popu.append(np.array([0,1,3,0,5,4,2,3,0,1]))

popu

[array([5, 4, 2, 1, 5, 0, 3, 1, 2, 5]),
 array([3, 3, 4, 2, 2, 0, 0, 3, 2, 3]),
 array([2, 1, 2, 2, 4, 0, 5, 1, 1, 4]),
 array([5, 2, 4, 1, 5, 4, 3, 4, 5, 5]),
 array([3, 1, 2, 3, 4, 1, 2, 1, 5, 0]),
 array([1, 0, 5, 1, 2, 3, 1, 1, 1, 1]),
 array([0, 1, 3, 0, 5, 4, 2, 3, 0, 1])]

In [45]:
#function to update the towers based on the action

def update(action, t1,t2,t3):
    """
    Function to update the towers based on the action
    """
    if action == 0: #from t1 to t2
        t2.append(t1.pop())
        return(t1,t2, t3)
    elif action == 1:  #from t1 to t3
        t3.append(t1.pop())
        return(t1,t2, t3)
    elif action == 2:  #from t2 to t1
        t1.append(t2.pop())
        return(t1,t2, t3)
    elif action == 3:  #from t2 to t3
        t3.append(t2.pop())
        return(t1,t2, t3)
    elif action == 4:  #from t3 to t1
        t1.append(t3.pop())
        return(t1,t2, t3)
    elif action == 5:  #from t3 to t2
        t2.append(t3.pop())
        return(t1,t2, t3)
    else:
        pass
        

In [46]:
def possible_action(action, ta, tb, tc):
    """
    Already avoids poping from empty list
    Already avoids the smaller disk on larger ones
    """
    t1 = ta.copy()
    t2 = tb.copy()
    t3 = tc.copy()
    try:
        if action == 0: #from t1 to t2
            t2.append(t1.pop())
        elif action == 1:  #from t1 to t3
            t3.append(t1.pop())
        elif action == 2:  #from t2 to t1
            t1.append(t2.pop())
        elif action == 3:  #from t2 to t3
            t3.append(t2.pop())
        elif action == 4:  #from t3 to t1
            t1.append(t3.pop())
        elif action == 5:  #from t3 to t2
            t2.append(t3.pop())
        else:
            pass
        
        if check_weigth(t1) or check_weigth(t2) or check_weigth(t3):
            return False
        else:
            return True
        
    except:
        return False

In [47]:
def check_weigth2(t):
    """
    Funtion to check that there is no small disk below a large one
    If there is one then return true
    """
    l = len(t)
    if l == 0:
        return False
    elif l == 1:
        return False
    elif l == 2:
        if t[1] > t[0]:
            return True
        else:
            return False
    elif l == 3:
        if t[1] > t[0]:
            return True
        elif t[2] > t[1]:
            return True
        else:
            return False

In [876]:
def check_weigth(t):
    """
    Funtion to check that there is no small disk below a large one
    If there is one then return true
    """
    val = False
    for i in range(len(t)-1):
        if t[i] < t[i+1]:
            val = True
            break
    return val

In [880]:
#Testing
check_weigth([4,3,2,1])

False

In [55]:
#testing -> 
t1 = [3,2]
t2 = [1]
t3 = []

if possible_action(1, t1,t2,t3):
    print( update(1, t1,t2,t3))
else:
    print ("no se puede")

([3], [1], [2])


In [486]:
def eval_towers(t3, n, pos):
    """
    Function that evalutes the solution
    Evaluates solutions that complete the towers
    Evalutes solutions that didn't complete the towers
    Three portions: 
        1 -> evaluates the number of steps
        2 -> evaluates the number of disk on t3
        3 -> evalutes the weight of disks on t3
    """
    steps_object = 2**n-1
    weight_object = sum(np.arange(n)+1)
    if weight_object == sum(t3):
        return ((sum(t3)/(pos+1))+10)
    else:
        return (sum(t3)/(pos+1)) 

    #return len(t3)/(pos+1) + len(t3)/n + sum(t3)/sum(np.arange(n)+1)

**Testing the evaluation of a population**

In [487]:
n = 3
#analyze each chromosome
for pop in popu:
    #create towers for each solution
    steps = 0
    t1,t2,t3 = create_towers(n)
    #analyze each action of the chromosome
    for i in range (len(pop)):
        #check if the action is posible given the constraints
        if possible_action(pop[i], t1, t2, t3):
            #If so, then update the towers, done in the condition
            t1,t2,t3 = update(pop[i], t1, t2, t3)
            steps += 1
        else:
            #If no,keep going
            pass
        #If the tower 3 is completed then no need to complete the other actions
        if len(t3) == n:
            break
    #then evaluates the chromosome
    print(eval_towers(t3, n, steps), t3, steps)

0.0 [] 4
0.3333333333333333 [1] 2
0.0 [] 5
0.0 [] 4
0.0 [] 4
10.75 [3, 2, 1] 7
0.45454545454545453 [3, 2] 10


In [496]:
def eval_tunned(individual,problem):
    """
    Functiont that takes 1 individual and returns its corresponding evaluation to the problem
    """
    #count of steps
    steps = 0
    #create towers
    t1,t2,t3 = create_towers(problem.n)
    for i in range (len(individual)):
        #check if the action is posible given the constraints
        if possible_action(individual[i], t1, t2, t3):
            #If so, then update the towers, done in the condition
            t1,t2,t3 = update(individual[i], t1, t2, t3)
            steps += 1
        else:
            #If no,keep going
            pass
        #If the tower 3 is completed then no need to complete the other actions
        if len(t3) == problem.n:
            break
    #then evaluates the chromosome
    return eval_towers(t3, problem.n, steps)

In [60]:
#testing possible solutions manually
t1 = [3,2,1]
t2 = []
t3 = []
sol = [1,0,5,1,2,3,1,1,1,1]
solp = [0, 1, 3, 0, 5, 4, 2, 3, 0, 1]
tes = [0, 1, 3, 0, 5, 4, 2, 3, 0, 1]

print(t1,t2,t3)
t1,t2,t3 = update(tes[0], t1, t2, t3)
print(t1,t2,t3)
t1,t2,t3 = update(tes[1], t1, t2, t3)
print(t1,t2,t3)
t1,t2,t3 = update(tes[2], t1, t2, t3)
print(t1,t2,t3)
t1,t2,t3 = update(tes[3], t1, t2, t3)
print(t1,t2,t3)
t1,t2,t3 = update(tes[4], t1, t2, t3)
print(t1,t2,t3)
t1,t2,t3 = update(tes[5], t1, t2, t3)
print(t1,t2,t3)
t1,t2,t3 = update(tes[6], t1, t2, t3)
print(t1,t2,t3)
t1,t2,t3 = update(tes[7], t1, t2, t3)
print(t1,t2,t3)
t1,t2,t3 = update(tes[8], t1, t2, t3)
print(t1,t2,t3)
t1,t2,t3 = update(tes[9], t1, t2, t3)
print(t1,t2,t3)

[3, 2, 1] [] []
[3, 2] [1] []
[3] [1] [2]
[3] [] [2, 1]
[] [3] [2, 1]
[] [3, 1] [2]
[2] [3, 1] []
[2, 1] [3] []
[2, 1] [] [3]
[2] [1] [3]
[] [1] [3, 2]


# Genetic algorithm code

In [61]:
# Implements the random initialization of individuals using the binary representation.
def createIndividual(nbBits):
    return np.random.randint(6, size = nbBits)

In [64]:
#from teacher code
# Implements the one point crossover on individuals using the binary representation.
import random
import numpy

def combine(parentA, parentB, cRate):
    """
    cRate  = value to allow combination the higher the higher allowance
    Note that cPoint is randomly selected, there is no preference for the first part of the code
    """
    if (random.random() <= cRate):
        cPoint = numpy.random.randint(1, len(parentA))   
        offspringA = numpy.append(parentA[0:cPoint], parentB[cPoint:])
        offspringB = numpy.append(parentB[0:cPoint], parentA[cPoint:])
    else:
        offspringA = numpy.copy(parentA)
        offspringB = numpy.copy(parentB)
    return offspringA, offspringB

In [65]:
# Implements the flip mutation on individuals using the binary representation.
def mutate(individual, mRate):
    """
    Note that the randint has a range, it can be changed depending on the problem
    """
    for i in range(len(individual)):
        if (random.random() <= mRate):
            individual[i] = random.randint(0, 5)
    return individual

In [66]:
# Implements the tournament selection.
def select(population, evaluation, tournamentSize):
    winner = numpy.random.randint(0, len(population))
    for i in range(tournamentSize - 1):
        rival = numpy.random.randint(0, len(population))
        if (evaluation[rival] > evaluation[winner]):
            winner = rival
    return population[winner]

In [852]:
#Code from teacher but updated
def geneticAlgorithm(problem, populationSize, generations, cRate, mRate):
    # Creates the initial population (it also evaluates it)
    population = [None] * populationSize
    evaluation = [None] * populationSize  
    for i in range(populationSize):
        individual = createIndividual(problem.length)
        population[i] = individual
        evaluation[i] = eval_tunned(individual, problem) 
    # Keeps a record of the best individual found so far
    index = 0;
    for i in range(1, populationSize):
        if (evaluation[i] > evaluation[index]):
            index = i;
    bestIndividual = population[index]
    bestEvaluation = evaluation[index]
    # Runs the evolutionary process    
    for i in range(generations):
        k = 0
        newPopulation = [None] * populationSize    
        for j in range(populationSize // 2):
            parentA = select(population, evaluation, 3)
            parentB = select(population, evaluation, 3)
            newPopulation[k], newPopulation[k + 1] = combine(parentA, parentB, cRate)       
            k = k + 2    
        population = newPopulation
        for i in range(populationSize):
            population[i] = mutate(population[i], mRate)
            evaluation[i] = eval_tunned(population[i], problem)
            # Keeps a record of the best individual found so far
            if (evaluation[i] > bestEvaluation):
                bestEvaluation = evaluation[i]
                bestIndividual = population[i]
    return bestIndividual, bestEvaluation

In [447]:
#Definition of the class of for the problem 
class problema:
    """
    length = the length of the individual
    n = number of towers
    """
    def __init__(self, length, n):
        self.length = length
        self.n =  n

In [449]:
def move(pos):
    """
    Function to return the movement
    """
    if pos == 0: #from t1 to t2
        return "From T1 to T2"
    elif pos == 1:  #from t1 to t3
        return "From T1 to T3"
    elif pos == 2:  #from t2 to t1
        return "From T2 to T1"
    elif pos == 3:  #from t2 to t3
        return "From T2 to T3"
    elif pos == 4:  #from t3 to t1
        return "From T3 to T1"
    elif pos == 5:  #from t3 to t2
        return "From T3 to T2"
    else:
        pass

In [450]:
def print_solution(n, solution):
    """
    Function to print the solution
    """
    #create towers for each solution
    t1,t2,t3 = create_towers(n)
    #analyze each action of the chromosome
    print(t1,t2,t3)
    for i in range (len(solution)):
        #check if the action is posible given the constraints
        if possible_action(solution[i], t1, t2, t3):
            #If so, then update the towers, done in the condition
            t1,t2,t3 = update(solution[i], t1, t2, t3)
            print(move(solution[i]),t1,t2,t3)
        else:
            #If no,keep going
            pass
        #If the tower 3 is completed then no need to complete the other actions
        if len(t3) == n:
            break    

# Testing the genetic algorithm

In [936]:
# Before running the code, we must initialize the random number generators.
#numpy.random.seed(42)
#random.seed(numpy.random.randint(10000))
# Generates a problem with individual lenght and number of towers
n = 3
length = 20
p1 = problema(length, n)
# solves the problem using the genetic algorithm
solution, evaluation = geneticAlgorithm(p1, 20, 50, 0.1, 0.7)
print(solution)
print(evaluation)
print_solution(n, solution)

[3 1 0 3 5 1 2 3 3 1 3 5 5 0 0 4 2 0 3 4]
10.75
[3, 2, 1] [] []
From T1 to T3 [3, 2] [] [1]
From T1 to T2 [3] [2] [1]
From T3 to T2 [3] [2, 1] []
From T1 to T3 [] [2, 1] [3]
From T2 to T1 [1] [2] [3]
From T2 to T3 [1] [] [3, 2]
From T1 to T3 [] [] [3, 2, 1]


Testing the solution again

In [514]:
#channge individual for the solution
individual = [1, 0, 4, 0, 1, 2, 0, 2, 3, 4, 4, 3, 2, 3, 4, 0, 0, 0, 3, 4]
#count of steps
steps = 0
#create towers
t1,t2,t3 = create_towers(p1.n)
for i in range (len(individual)):
    #check if the action is posible given the constraints
    if possible_action(individual[i], t1, t2, t3):
        #If so, then update the towers, done in the condition
        t1,t2,t3 = update(individual[i], t1, t2, t3)
        steps += 1
    else:
        #If no,keep going
        pass
    #If the tower 3 is completed then no need to complete the other actions
    if len(t3) == p1.n:
        break

print(t3,steps)

steps_object = 2**p1.n-1
weight_object = sum(np.arange(p1.n)+1)
if weight_object == sum(t3):
    print ((sum(t3))/(steps+1)+10)
else:
    print ((sum(t3))/(steps+1))

[3, 2, 1] 11
10.5


# 1st Part of the genetic works

In [627]:
# Creates the initial population (it also evaluates it)
populationSize = 20
problem = p1

population = [None] * populationSize
evaluation = [None] * populationSize  
for i in range(populationSize):
    individual = createIndividual(problem.length)
    population[i] = individual
    evaluation[i] = eval_tunned(individual, problem) 
# Keeps a record of the best individual found so far
index = 0;
for i in range(1, populationSize):
    if (evaluation[i] > evaluation[index]):
        index = i;
bestIndividual = population[index]
bestEvaluation = evaluation[index]

print(bestIndividual,bestEvaluation)
print_solution(3,bestIndividual)

[1 3 2 2 3 0 5 1 1 3 4 3 5 3 3 1 0 2 2 3] 10.545454545454545
[3, 2, 1] [] []
From T1 to T3 [3, 2] [] [1]
From T1 to T2 [3] [2] [1]
From T3 to T2 [3] [2, 1] []
From T1 to T3 [] [2, 1] [3]
From T2 to T3 [] [2] [3, 1]
From T3 to T1 [1] [2] [3]
From T2 to T3 [1] [] [3, 2]
From T3 to T2 [1] [2] [3]
From T2 to T3 [1] [] [3, 2]
From T1 to T3 [] [] [3, 2, 1]
[3 3 4 4 3 0 0 4 2 3 0 1 0 0 0 3 3 3 4 1]


In [692]:
#saving for testing
best_init_ind = bestIndividual
best_init_eval = bestEvaluation
print(best_init_ind,best_init_eval)

[1 3 2 2 3 0 5 1 1 3 4 3 5 3 3 1 0 2 2 3] 10.545454545454545


# 2nd part of the genetic

In [851]:
generations = 3
mRate = 0.1
cRate = 0.9
bestIndividual = best_init_ind
bestEvaluation = best_init_eval

# Runs the evolutionary process    
for i in range(generations):
    k = 0
    newPopulation = [None] * populationSize    
    for j in range(populationSize // 2):
        parentA = select(population, evaluation, 3)
        parentB = select(population, evaluation, 3)
        newPopulation[k], newPopulation[k + 1] = combine(parentA, parentB, cRate)       
        k = k + 2    
    population = newPopulation
    for i in range(populationSize):
        population[i] = mutate(population[i], mRate)
        evaluation[i] = eval_tunned(population[i], problem)
        # Keeps a record of the best individual found so far
        if (evaluation[i] > bestEvaluation):
            bestEvaluation = evaluation[i]
            bestIndividual = population[i]
            print("entre")

print(bestIndividual,bestEvaluation)

entre
[3 3 3 4 3 2 3 1 1 2 0 5 1 2 3 1 5 1 1 1] 10.75


In [849]:
newPopulation

[array([1, 3, 1, 1, 3, 2, 3, 1, 1, 2, 0, 5, 1, 2, 3, 4, 3, 1, 3, 3]),
 array([4, 3, 3, 1, 3, 2, 3, 1, 1, 2, 0, 5, 1, 2, 5, 3, 2, 0, 0, 4]),
 array([1, 3, 1, 1, 3, 1, 3, 1, 1, 2, 0, 5, 1, 2, 3, 1, 5, 1, 0, 3]),
 array([1, 3, 3, 1, 3, 2, 1, 1, 1, 2, 0, 5, 1, 2, 3, 2, 0, 1, 3, 3]),
 array([2, 3, 3, 1, 3, 1, 1, 1, 1, 3, 0, 5, 1, 1, 5, 2, 0, 1, 3, 3]),
 array([1, 3, 1, 1, 3, 2, 3, 1, 1, 2, 0, 5, 3, 2, 3, 5, 5, 1, 0, 2]),
 array([1, 3, 1, 1, 3, 2, 3, 1, 1, 2, 0, 3, 1, 2, 5, 1, 0, 1, 3, 3]),
 array([1, 3, 2, 1, 3, 2, 3, 0, 1, 2, 0, 5, 1, 2, 3, 2, 0, 1, 3, 3]),
 array([4, 3, 1, 1, 3, 2, 3, 1, 1, 2, 0, 5, 1, 2, 3, 0, 3, 1, 3, 2]),
 array([4, 3, 3, 1, 3, 2, 3, 1, 1, 2, 0, 5, 2, 1, 5, 1, 5, 1, 0, 3]),
 array([1, 0, 2, 1, 3, 1, 3, 1, 1, 2, 4, 5, 1, 2, 3, 2, 0, 1, 3, 3]),
 array([1, 3, 1, 1, 1, 5, 3, 1, 1, 2, 0, 5, 1, 1, 0, 1, 0, 1, 0, 3]),
 array([1, 1, 3, 1, 3, 2, 3, 1, 1, 2, 0, 5, 1, 5, 3, 3, 0, 1, 3, 3]),
 array([3, 3, 3, 1, 3, 2, 3, 1, 1, 2, 0, 5, 1, 2, 3, 1, 5, 1, 3, 3]),
 array([4, 3, 3, 1, 

In [710]:
#channge individual for the solution
individual = [1, 3, 2, 2, 3, 0, 5, 1, 1, 3, 4, 3, 5, 3, 3, 1, 0, 2, 2, 3]
#count of steps
steps = 0
#create towers
t1,t2,t3 = create_towers(p1.n)
for i in range (len(individual)):
    #check if the action is posible given the constraints
    if possible_action(individual[i], t1, t2, t3):
        #If so, then update the towers, done in the condition
        t1,t2,t3 = update(individual[i], t1, t2, t3)
        steps += 1
    else:
        #If no,keep going
        pass
    #If the tower 3 is completed then no need to complete the other actions
    if len(t3) == p1.n:
        break

print(t3,steps)

steps_object = 2**p1.n-1
weight_object = sum(np.arange(p1.n)+1)
if weight_object == sum(t3):
    print ((sum(t3))/(steps+1)+10)
else:
    print ((sum(t3))/(steps+1))

[3, 2, 1] 10
10.545454545454545
